// Code generated by goctl. DO NOT EDIT.
package types

type EmailCodeRequest struct {
	Email string `json:"email"` // 邮箱
}

type EmailCodeReply struct {
	Code int `json:"code"`
}

type UserRegisterRequest struct {
	Name     string `json:"name"`     // 用户名
	Password string `json:"password"` // 密码
	Email    string `json:"email"`    // 邮箱
	Code     string `json:"code"`     // 验证码
}

type UserRegisterReply struct {
	Code int `json:"code"`
}

type UserLoginRequest struct {
	Name     string `json:"name"`     // 用户名
	Password string `json:"password"` // 密码
}

type UserLoginReply struct {
	Code int                `json:"code"`
	Data UserLoginReplyData `json:"data"`
}

type UserLoginReplyData struct {
	Token        string `json:"token"`         // token
	RefreshToken string `json:"refresh_token"` // refreshToken
}

type UserInfoRequest struct {
}

type UserInfoReply struct {
	Code int               `json:"code"`
	Data UserInfoReplyData `json:"data"`
}

type UserInfoReplyData struct {
	Name        string `json:"name"`         // 用户名
	Email       string `json:"email"`        // 邮箱
	NowVolume   int64  `json:"now_volume"`   // 当前容量
	TotalVolume int64  `json:"total_volume"` // 总容量
}

type RefreshTokenRequest struct {
}

type RefreshTokenReply struct {
	Code int                   `json:"code"`
	Data RefreshTokenReplyData `json:"data"`
}

type RefreshTokenReplyData struct {
	Token        string `json:"token"`         // token
	RefreshToken string `json:"refresh_token"` // refreshToken
}

type FileListRequest struct {
	Fid  string `json:"fid,optional"`
	Page int    `json:"page,optional"`
	Size int    `json:"size,optional"`
}

type FileListReply struct {
	Code int               `json:"code"`
	Data FileListReplyData `json:"data"`
}

type FileListReplyData struct {
	Pid   string   `json:"pid"`
	List  []*Files `json:"list"`
	Total int64    `json:"total"`
}

type Files struct {
	Fid    string `json:"fid"`
	Name   string `json:"name"`
	Ext    string `json:"ext"`
	Type   int    `json:"type"`
	Url    string `json:"url"`
	Number int    `json:"number"`
	Size   int64  `json:"size"`
}

type FileRenameRequest struct {
	Fid  string `json:"fid"`
	Name string `json:"name"`
}

type FileRenameReply struct {
	Code int `json:"code"`
}

type FolderCreateRequest struct {
	Pid  string `json:"pid,optional"`
	Name string `json:"name"`
}

type FolderCreateReply struct {
	Code int                   `json:"code"`
	Data FolderCreateReplyData `json:"data"`
}

type FolderCreateReplyData struct {
	Fid string `json:"fid"`
}

type FileDeleteRequest struct {
	Fid string `json:"fid"`
}

type FileDeleteReply struct {
	Code int `json:"code"`
}

type FileMoveRequest struct {
	Fid string `json:"fid"`
	Pid string `json:"pid"`
}

type FileMoveReply struct {
	Code int `json:"code"`
}

type FileShareRequest struct {
	Fid     string `json:"fid"`
	Expired int64  `json:"expired"`
	Encrypt string `json:"encrypt,optional"`
}

type FileShareReply struct {
	Code int                `json:"code"`
	Data FileShareReplyData `json:"data"`
}

type FileShareReplyData struct {
	Sid string `json:"sid"`
}

type ShareInfoRequest struct {
	Sid     string `json:"sid"`
	Encrypt string `json:"encrypt,optional"`
}

type ShareInfoReply struct {
	Code int                `json:"code"`
	Data ShareInfoReplyData `json:"data"`
}

type ShareInfoReplyData struct {
	Name    string `json:"name"`
	Ext     string `json:"ext"`
	Size    int64  `json:"size"`
	Url     string `json:"url"`
	Type    int    `json:"type"`
	Expired int64  `json:"expired"`
	Browse  int    `json:"browse"`
}

type ShareSaveRequest struct {
	Sid     string `json:"sid"`
	Pid     string `json:"pid"`
	Encrypt string `json:"encrypt,optional"`
}

type ShareSaveReply struct {
	Code int                `json:"code"`
	Data ShareSaveReplyData `json:"data"`
}

type ShareSaveReplyData struct {
	Fid string `json:"fid"`
}

type FileUploadRequest struct {
}

type FileUploadReply struct {
	Code int                 `json:"code"`
	Data FileUploadReplyData `json:"data"`
}

type FileUploadReplyData struct {
	Fid string `json:"fid"`
}

type InitPartRequest struct {
	Pid  string `json:"pid"`
	Md5  string `json:"md5"`
	Name string `json:"name"`
}

type InitPartReply struct {
	Code int               `json:"code"`
	Data InitPartReplyData `json:"data"`
}

type InitPartReplyData struct {
	Fid      string `json:"fid"`
	UploadId string `json:"upload_id"`
}

type UploadPartRequest struct {
}

type UploadPartReply struct {
	Code int `json:"code"`
}

type CompletePartRequest struct {
	UploadId string `json:"upload_id"`
}

type CompletePartReply struct {
	Code int                   `json:"code"`
	Data CompletePartReplyData `json:"data"`
}

type CompletePartReplyData struct {
	Fid string `json:"fid"`
}
